### ISSUE TITLE
Something went wrong: Service script.play_music not found.

### ISSUE THREAD

**Issue by Clinteastman** [FutureProofHomes/wyoming-enhancements#16]
Everything works, all the way up to the point of steaming the track and then I get "Something went wrong: Service script.play_music not found."

script.play_music is available and when I ask the assistant if if has accesses it says it has. If I tell it to run the script I can see in the history it was run?

**Comment by absarbandayy** [comment]
check the automation and script pannel ... in scripts run the play music script

**Comment by Clinteastman** [comment]
If I manually run the script it starts playing the default music to the default device.

**Comment by Clinteastman** [comment]
Ok so I found a workaround.

I duplicated the script and renamed it to run_music. I then just updated the spec to call that script and now it works a treat.

**Comment by absarbandayy** [comment]
@Clinteastman I have a issue with my code can you help me with it

**Comment by Clinteastman** [comment]
I can try, what's the problem?

**Comment by absarbandayy** [comment]
I can't hear any response from the AI

**Comment by Clinteastman** [comment]
Start a new issue for it.

**Comment by FutureProofHomes** [comment]
@absarbandayy thanks for opening another ticket.  Let's keep your conversation there.

@Clinteastman glad you figured it out.  If you create a script called `stranger _things` then homeassistant will have an entity named `script.stranger_things`.  BUT if you then change the name of the script in the automation UI to "the_upside_down", the script will still be called `script.stranger_things`.

I mention all this because I'm betting your original "play_music" script didn't really have an entity name of `script.play_music`.

Closing this ticket.  Thnx!
